language: python
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
install:
- pip install -r requirements.txt
script:
- python -m unittest discover -s tests
deploy:
  provider: pypi
  username: __token__
  password:
    secure: RK02iHnVp7f/yK/EH6Go0JciqsOoDY7u8WVaB/SRv59c/f8oAvXDa9d/5MsSRFwpPI0Ilc+5LpNIZj2RuPDdegi6OknQ+cJoHeEPD9+qOCrnnTmgSkrNcMG8qBOjbIzRuPW4TVhkqcIEuh5eFmsMoSUolAHR65vJm4PYTwzzFdh1uZyKFBJuiGvYaBul8XL2tEIRm3bmEmxJbUZQAooX1GdSw7OGp0nB2t3i0cdfK90Atbmr51DecRIQ6JZLJInP+cAVDHt8Wz8YElYvBRsl4OfwwEknynZHB8iMr9vNVjTN9GCjKlFrHWfcPwzm5yn2cnJY4oNqKNQICwIkWSpTUygUZ1Y6h4VgHQxA02kXK8I3+Ux9cpm0fLPFvolXb2BIowV+lwOia0rmKJJRHxO6cNKEBV1UXlFBQgOZEsKT3SZ9W32YzdFzDBJRyKftnCxfMMzxIwfAEubamEU3KI2291DTF43ZpWeb+JYTsH2lxy7W2OzuuMVUaj0DrlpGD1spYrDawNx+vqS8hSF6vpUVehvfbU3unhztOlzIBGt8edGd8mqKgxSSHd1FctAtEJCYHsd7o85ImtWaxKE2MSabtOAqmHiB5eGOKaEs8bvLmK9nnz522MpgaxTtqxbZIhc4N31r0t8tRiCllg9BDXal+K5AbAcDMXbu+I4gDdGht04=
