language: python
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
install:
- pip install -r requirements.txt
script:
- python -m unittest discover -s tests
deploy:
  provider: pypi
  username: __token__
  password:
    secure: aHtJ7uxWmtU0psiqYIA1YOVYADVCxk31M2XL0Ou8ppPNAkWnHPWEcaQKWLp7t4xnXpSG0zFyB3gI83cUrIv2b7hP2+nH9xA89sV1DNA0jIrqJ4zOys5UOcpPWHC0/Drmfwn5weHqSFWO5kKLHORppcyjVHs9XlWuYubnfettZKsA5UVHfhF0JB7XA4d6ntXUzCgoWGpZe4wXvTBKI1Xp4HesxRQ3HOR9R8AbWddO7B2aegi6kS3+odbwAGX2hgdiqBwf+gTnCLEw8p3yecxWBFThmuLlC5EiN3Pzl/EW+oNbKIhdgHmjCbZ09uJhToaeOF8EBZy8QQrs1HmNawi+DLudtTgTfB+1Cyc1o6JtUvaouEpYGDJZWyG19vwPcU7+Ao09kqkQtDHBFadIQt7dDcta0Rfug3GlxoUkkQc1uCld9WOQJvHm+WRigNTq/M4BeUedPNf8UNxc9NVXVZ5aSvXHlPor2/CLP70V/gi0kJeEU2dl4sjNoC/RZbbT7enffdzrIWBpaZzchsZty11dPDGjmzQD77GopZQedTj9wSEMHbKUyDCBiSr8Ln0IOcNHcBiDRzQTqWCVZlUZDl4bKOLem3whdBtQISZG6yOZ//8lIeWKG4F8HV//C7hUIUkc18NrpL/Pht+aPbEZyOIIvyJ4wjlaM2EbS48VZLR8JHI=
